### ISSUE TITLE
Can't figure out this 400 Error

### ISSUE THREAD

**Issue by latifs** [bennycode/coinbase-pro-node#639]
Hi @bennycode,

First thanks for the hard work this is an awesome project.

Unfortunately I do seem to have come to a dead end in my project and can't figure out the issue at this point.
I'm trying to place an order using the rest client and this is what I get back:

```(node:13720) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (.../node_modules/coinbase-pro-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (.../node_modules/coinbase-pro-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (.../node_modules/coinbase-pro-node/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:13720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:13720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the Api call I'm making:
```
const order = await this.client.rest.order.placeOrder(data)
```

This is the data I'm passing to the call: 
```
data:  {
  product_id: 'SOL-USD',
  type: 'market',
  client_oid: '0ceca3ed-2591-42a8-8051-c5631eebc780',
  funds: 10
}
```

Any ideas?

Thanks again

**Comment by bennycode** [comment]
Hi @latifs, can you please add a `catch` to your `placeOrder` call or surround it by a `try-catch`, so that we can see the `error.message`?

**Comment by latifs** [comment]
For sure @bennycode,

here's my whole function:

```
async buy({ price, funds }) {
    if (!this.isLive) {
      return { size: funds / price, price: price };
    }

    if (this.state !== 'running') return null;
    this.state = 'buying';  //update my state

    const token = uuidv4();
    this.tokens[token] = 'buy';

    const lock = () => {
      return new Promise((resolve, reject) => {
        this.callbacks[token] = resolve;
      });
    };

    try {
      const data = this.generateMarketData({ token, funds });
      const order = await this.client.rest.order.placeOrder(data);

      console.log('order:', order);

      if (order.message) {
        this.state = 'running';
        throw new Error(order.message);
      }

      const filled = await lock();
      this.state = 'running';
      return filled;
    } catch (error) {
      this.state = 'running';
      throw error;
    }
  }
```

the `generateMarketData` function returns this data:

```
data:  {
  product_id: 'SOL-USD',
  type: 'market',
  client_oid: '0ceca3ed-2591-42a8-8051-c5631eebc780',
  funds: 10
}
```

Unless it is coming from somewhere else, I'm not quite sure but the error appears right around I place the order.

**Comment by latifs** [comment]
@bennycode,
I'm realizing now that the error could be coming from my `Feed` which I actually call In my constructor in the class in the previous code I sent.

```
const {
  CoinbasePro,
  WebSocketChannelName,
  WebSocketEvent,
} = require('coinbase-pro-node');

const config = require('../../configuration');

class Feed {
  constructor({ product, onUpdate, onError }) {
    this.product = product;
    this.onUpdate = onUpdate;
    this.onError = onError;
    this.running = false;
  }

  async start() {
    this.running = true;
    this.client = new CoinbasePro({
      apiKey: config.get('API_KEY'),
      apiSecret: config.get('API_SECRET'),
      passphrase: config.get('API_PASSPHRASE'),
      useSandbox: config.get('API_USE_SANDBOX'),
    });

    const channelUser = {
      name: WebSocketChannelName.USER,
      product_ids: [this.product],
    };

    const channelHeartbeat = {
      name: WebSocketChannelName.HEARTBEAT,
      product_ids: [this.product],
    };

    // ON_OPEN, we subscribe
    this.client.ws.on(WebSocketEvent.ON_OPEN, () => {
      this.client.ws.subscribe([channelUser, channelHeartbeat]);
    });

    // ON_MESSAGE
    this.client.ws.on(WebSocketEvent.ON_MESSAGE, (response) => {
      // console.log('response:', response);
      if (response.type === 'heartbeat') return;
      this.onUpdate(response);
    });

    // ON_ERROR
    this.client.ws.on(WebSocketEvent.ON_ERROR, (event) => {
      this.onError(event);
      this.client.ws.connect();
    });

    //ON_CLOSE
    this.client.ws.on(WebSocketEvent.ON_CLOSE, (event) => {
      if (this.running) {
        this.client.ws.connect();
      }
    });

    //we connect
    this.client.ws.connect();
  }

  stop() {
    this.running = false;
    this.client.ws.disconnect();
  }
}

module.exports = exports = Feed;
```

**Comment by bennycode** [comment]
Hi @latifs, I got the stacktrace from you and the info that it is a HTTP error 400. Can you also get me the exact error message? You can get this by adding the following on top of your code:

```ts
process.on('unhandledRejection', error => {
  console.log('here comes the error message', error.message);
});

```
