### ISSUE TITLE
Having trouble accessing listCoinBaseAccounts()

### ISSUE THREAD

**Issue by kenchambers** [bennycode/coinbase-pro-node#677]
Greetings.

Set up example exactly as outlined in docs, got valid sandbox keys , and then tried hitting the following api:

`client.rest.account.listCoinbaseAccounts()`

But I am not seeing anything triggered. It is also not triggering my catch, which smells. maybe i am being silly and handling the promise wrong?

See sandbox below: 

https://codesandbox.io/s/setup-basic-node-js-server-forked-zs5gv?file=/index.js

The response returns nothing. Could be a mishap on the way I have async set up, but any help would be much appreciated. thanks

**Comment by kenchambers** [comment]
realized missing param accountId after checking source code

**Comment by kenchambers** [comment]
@bennycode  I see the same thing for `listCoinbaseAccounts()`

you can see in the code pen that I am doing this. 

I tried without the try catch as well.

https://codesandbox.io/s/setup-basic-node-js-server-forked-zs5gv?file=/index.js

sorry i mislabeled this issue, I have received blank returns from `getAccount` `listAccounts` and `listCoinbaseAccounts` using the same keys.

**Comment by hjoelr** [comment]
@kenchambers It could be that you're using the sandbox and not live. Have you tried this on a valid API key with `sandbox: false`?

**Comment by hjoelr** [comment]
@kenchambers Were you able to get this figured out?

**Comment by kenchambers** [comment]
@hjoelr 

thanks again for your help.

Using a valid API key, passphrase and secret from my own personal pro.coinbase.com account. i ran:

`await this.client.rest.account.listCoinbaseAccounts();`

and i am getting:
```
Unauthorized.
Request failed with status code 401
```

details of response:  ( XXX replace sensitive information )
```js
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Request failed with status code 401
      at createError (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/adapters/http.js:293:11)
      at IncomingMessage.emit (node:events:406:35)
      at endReadableNT (node:internal/streams/readable:1329:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 50000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      baseURL: 'https://api.pro.coinbase.com',
      method: 'get',
      url: '/coinbase-accounts',
      'axios-retry': [Object],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /coinbase-accounts HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'CB-ACCESS-KEY: \r\n' +
        'CB-ACCESS-PASSPHRASE: \r\n' +
        'CB-ACCESS-SIGN: XXXXXXXXX=\r\n' +
        'CB-ACCESS-TIMESTAMP: 1643355238.699\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: api.pro.coinbase.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/coinbase-accounts',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.pro.coinbase.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 401,
      statusText: 'Unauthorized',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
} reason: Error: Request failed with status code 401
    at createError (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 50000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'CB-ACCESS-KEY': '',
      'CB-ACCESS-PASSPHRASE': '',
      'CB-ACCESS-SIGN': 'XxXXXXXXXXXXXX',
      'CB-ACCESS-TIMESTAMP': '1643355238.699',
      'User-Agent': 'axios/0.24.0'
    },
    baseURL: 'https://api.pro.coinbase.com',
    method: 'get',
    url: '/coinbase-accounts',
    'axios-retry': { retryCount: 0, lastRequestTime: 1643355238421 },
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.pro.coinbase.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.pro.coinbase.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 50000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 79,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 50000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 2653,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 87,
        [Symbol(triggerId)]: 82
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /coinbase-accounts HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'CB-ACCESS-KEY: \r\n' +
      'CB-ACCESS-PASSPHRASE: \r\n' +
      'CB-ACCESS-SIGN: XXXXXXXXX=\r\n' +
      'CB-ACCESS-TIMESTAMP: 1643355238.699\r\n' +
      'User-Agent: axios/0.24.0\r\n' +
      'Host: api.pro.coinbase.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/coinbase-accounts',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.pro.coinbase.com/coinbase-accounts',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 42,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.pro.coinbase.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.pro.coinbase.com/coinbase-accounts',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'cb-access-key': [Array],
      'cb-access-passphrase': [Array],
      'cb-access-sign': [Array],
      'cb-access-timestamp': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Fri, 28 Jan 2022 07:33:59 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '27',
      connection: 'close',
      'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor',
      'access-control-allow-methods': 'GET,POST,DELETE,PUT',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'cb-before, cb-after, cb-gdpr',
      'access-control-max-age': '7200',
      'cache-control': 'no-store',
      etag: 'W/"1b-OTB0WjV/ub4RM7iikeBhQVBUCR0"',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'cf-cache-status': 'MISS',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      server: 'cloudflare',
      'cf-ray': 'XXXXXXXXXXXXXXX-IAD'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 50000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      baseURL: 'https://api.pro.coinbase.com',
      method: 'get',
      url: '/coinbase-accounts',
      'axios-retry': [Object],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /coinbase-accounts HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'CB-ACCESS-KEY: \r\n' +
        'CB-ACCESS-PASSPHRASE: \r\n' +
        'CB-ACCESS-SIGN: XXXXXXXXXXXXXXXXXXXXXXXX=\r\n' +
        'CB-ACCESS-TIMESTAMP: 1643355238.699\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: api.pro.coinbase.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/coinbase-accounts',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.pro.coinbase.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { message: 'Unauthorized.' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
} error: undefined
Error: Request failed with status code 401
    at createError (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/ken/Documents/GitHub/bot-farm/node_modules/coinbase-pro-node/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by hjoelr** [comment]
@kenchambers It appears that maybe you're still using `sandbox: true`. I just did a quick test on my computer and when I had `sandbox` set to true, I was getting a 401 error like you show. However, when I changed it to false (ie. using real Coinbase) it returned the accounts as expected. Here's my test code:

```TypeScript
const auth = {
  apiKey: "...",
  apiSecret: "...",
  passphrase: "...",
  useSandbox: false,
}

const client = new CoinbasePro(auth);

const accounts = await client.rest.account.listCoinbaseAccounts();

console.log(accounts);
```

**Comment by hjoelr** [comment]
Actually, I just noticed that you are using just `sandbox: false`. It should be `useSandbox: false`.

**Comment by kenchambers** [comment]
That was it! thank you so much @hjoelr i feel silly making a mistake like that!

**Comment by hjoelr** [comment]
👍 You're welcome. Ideally Coinbase would make their sandbox accounts have feature parity with the real thing. It mostly nullifies the purpose of a sandbox when they don't both operate the same way.

**Comment by bennycode** [comment]
@kenchambers the best advice here is to use TypeScript. With TypeScript you would see such errors before executing your code. It's really worth giving it a go. 🙂
